mysql:
  host: "127.0.0.1"
  user: "root"
  password: ""
  database: "my_server"

shipping-box:
  messages:
    inventory-title: "Sell your useless items!"
    scoreboard-title: "Box"
    scoreboard-separator: "======="
    scoreboard-item-count: "{ITEM_COUNT} item{ITEM_COUNT_PLURAL_1}"
    scoreboard-total-price: "{TOTAL_PRICE} $"
    open-message: "Drop the items you want to sell in this box!"
    sold-message: "Sold {ITEM_COUNT} item{ITEM_COUNT_PLURAL_1} for {TOTAL_PRICE} $."
    not-for-sale: "You can't sell {ITEM_NAME} through this box."
    cant-sell-enchant: "You can't sell enchanted items."
  item-of-the-day:
    signs:
      1:
        world: "world"
        name: [200, 64, -117]
        price: [200, 64, -116]
  signs:
    item-of-the-day-price-1: "$ {PRICE}"
    item-of-the-day-price-2: "each!"

item-bank:
  title: "Bank {ID}"
  messages:
    must-purchase: "To use this chest, you need to purchase it for {PRICE}."
    purchase-not-enough: "You don't have enough money at the moment."
    purchase-confirm: "Open this chest again to confirm the purchase."
    purchase-success: "You purchased this chest for {PRICE}."
    purchase-error: "An unexpected error occurred, try again later."

market:
  title: "Market"
  price-tag: "Price: ${PRICE}"
  buttons:
    left: "Left"
    right: "Right"
    page: "Page {PAGE}/{TOTAL}"
  messages:
    sell-usage: "/sell <price>"
    sell-success: "You've put {QUANTITY}x{MATERIAL} for sale at ${PRICE}."
    sold-notification: "You've sold {QUANTITY}x{MATERIAL} at ${PRICE}."
    invalid-price: "Invalid price: {PRICE}"
    invalid-item: "You must select an item to sell."
    sell-too-far: "You must be near the market to sell something."
    buy-success: "You've purchased {QUANTITY}x{MATERIAL} at ${PRICE}."
    buy-not-enough-money: "You don't have enough money."
    buy-too-late: "Too late, this item is no longer for sale."
    buy-no-space: "Your inventory is full."
    sql-error: "An unexpected error occurred, try again later."
